// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'AerosolOpticalPropertiesProductImpl.*' files.
// ***********************************************************************

#pragma once
#include "../../common/AttributeList.h"
#include "../../common/DataWriter.h"
#include "../../common/MemoryReader.h"
#include "../../grid/Typedefs.h"
#include "../ProductDefinition.h"
#include "HorizontalSettings.h"
#include "ParameterAerosolOpticalSettings.h"
#include "PointInTimeSettings.h"

namespace SmartMet {
namespace GRIB2 {
/*! \brief The class is automatically created from the template (4.48).*/

class AerosolOpticalPropertiesProduct : public ProductDefinition {
public:
  AerosolOpticalPropertiesProduct();
  ~AerosolOpticalPropertiesProduct() override;

  uint getTemplateNumber() const override;
  ProductDefinition *createProductDefinition() const override;
  void read(MemoryReader &memoryReader) override;
  void write(DataWriter &dataWriter) override;
  void getAttributeList(const std::string &prefix, T::AttributeList &attributeList) const override;
  void print(std::ostream &stream, uint level, uint optionFlags) const override;
  virtual T::Hash countHash();

  ParameterAerosolOpticalSettings *getParameterAerosolOptical() const;
  void setParameterAerosolOptical(ParameterAerosolOpticalSettings &parameterAerosolOptical);
  PointInTimeSettings *getPointInTime() const;
  void setPointInTime(PointInTimeSettings &pointInTime);
  HorizontalSettings *getHorizontal() const override;
  void setHorizontal(HorizontalSettings &horizontal);

protected:
  // # Copyright 2005-2019 ECMWF.
  //
  // # TEMPLATE 4.48, Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol
  //
  // include "grib2/template.4.parameter_aerosol_optical.def"

  mutable ParameterAerosolOpticalSettings mParameterAerosolOptical;

  // include "grib2/template.4.point_in_time.def"

  mutable PointInTimeSettings mPointInTime;

  // include "grib2/template.4.horizontal.def"

  mutable HorizontalSettings mHorizontal;
};

} // namespace GRIB2
} // namespace SmartMet
