// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'CrossSectionImpl.*' files.
// ***********************************************************************

#include "CrossSection.h"
#include "../../common/GeneralDefinitions.h"
#include "../../common/GeneralFunctions.h"
#include <macgyver/Hash.h>
#include <iostream>
#include <macgyver/Exception.h>

namespace SmartMet {
namespace GRIB2 {

/*! \brief The constructor of the class. */

CrossSection::CrossSection() {
  try {
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The destructor of the class. */

CrossSection::~CrossSection() {
}

/*! \brief The method reads and initializes all data related to the current object.

        \param memoryReader  This object controls the access to the memory mapped file.
*/

void CrossSection::read(MemoryReader &memoryReader) {
  try {
    mEarthShape.read(memoryReader);
    mNumberOfHorizontalPoints = memoryReader.read_UInt32_opt();
    mBasicAngleOfTheInitialProductionDomain = memoryReader.read_UInt32_opt();
    mSubdivisionsOfBasicAngle = memoryReader.read_UInt32_opt();
    mLatitudeOfFirstGridPoint = memoryReader.read_Int32_opt();
    mLongitudeOfFirstGridPoint = memoryReader.read_UInt32_opt();
    mScanningMode.read(memoryReader);
    mLatitudeOfLastGridPoint = memoryReader.read_Int32_opt();
    mLongitudeOfLastGridPoint = memoryReader.read_UInt32_opt();
    mTypeOfHorizontalLine = memoryReader.read_UInt8_opt();
    mNumberOfVerticalPoints = memoryReader.read_UInt16_opt();
    mMeaningOfVerticalCoordinate = memoryReader.read_UInt8_opt();
    mVerticalCoordinate = memoryReader.read_UInt8_opt();
    mNC = memoryReader.read_UInt16_opt();
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method writes all data related to the current object.

        \param dataWriter  This object is used for writing the object data.
*/

void CrossSection::write(DataWriter &dataWriter) {
  try {
    mEarthShape.write(dataWriter);
    dataWriter << mNumberOfHorizontalPoints;
    dataWriter << mBasicAngleOfTheInitialProductionDomain;
    dataWriter << mSubdivisionsOfBasicAngle;
    dataWriter << mLatitudeOfFirstGridPoint;
    dataWriter << mLongitudeOfFirstGridPoint;
    mScanningMode.write(dataWriter);
    dataWriter << mLatitudeOfLastGridPoint;
    dataWriter << mLongitudeOfLastGridPoint;
    dataWriter << mTypeOfHorizontalLine;
    dataWriter << mNumberOfVerticalPoints;
    dataWriter << mMeaningOfVerticalCoordinate;
    dataWriter << mVerticalCoordinate;
    dataWriter << mNC;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for collecting the current class attributeList.

    \param prefix         The prefix of the each attributeList parameter.
    \param attributeList  The attributeList storage.
*/

void CrossSection::getAttributeList(const std::string &prefix, T::AttributeList &attributeList) const {
  try {
    char name[300];
    sprintf(name, "%sCrossSection.", prefix.c_str());
    mEarthShape.getAttributeList(name, attributeList);
    sprintf(name, "%sCrossSection.NumberOfHorizontalPoints", prefix.c_str());
    attributeList.addAttribute(name, toString(mNumberOfHorizontalPoints));
    sprintf(name, "%sCrossSection.BasicAngleOfTheInitialProductionDomain", prefix.c_str());
    attributeList.addAttribute(name, toString(mBasicAngleOfTheInitialProductionDomain));
    sprintf(name, "%sCrossSection.SubdivisionsOfBasicAngle", prefix.c_str());
    attributeList.addAttribute(name, toString(mSubdivisionsOfBasicAngle));
    sprintf(name, "%sCrossSection.LatitudeOfFirstGridPoint", prefix.c_str());
    attributeList.addAttribute(name, toString(mLatitudeOfFirstGridPoint));
    sprintf(name, "%sCrossSection.LongitudeOfFirstGridPoint", prefix.c_str());
    attributeList.addAttribute(name, toString(mLongitudeOfFirstGridPoint));
    sprintf(name, "%sCrossSection.", prefix.c_str());
    mScanningMode.getAttributeList(name, attributeList);
    sprintf(name, "%sCrossSection.LatitudeOfLastGridPoint", prefix.c_str());
    attributeList.addAttribute(name, toString(mLatitudeOfLastGridPoint));
    sprintf(name, "%sCrossSection.LongitudeOfLastGridPoint", prefix.c_str());
    attributeList.addAttribute(name, toString(mLongitudeOfLastGridPoint));
    sprintf(name, "%sCrossSection.TypeOfHorizontalLine", prefix.c_str());
    attributeList.addAttribute(name, toString(mTypeOfHorizontalLine));
    sprintf(name, "%sCrossSection.NumberOfVerticalPoints", prefix.c_str());
    attributeList.addAttribute(name, toString(mNumberOfVerticalPoints));
    sprintf(name, "%sCrossSection.MeaningOfVerticalCoordinate", prefix.c_str());
    attributeList.addAttribute(name, toString(mMeaningOfVerticalCoordinate));
    sprintf(name, "%sCrossSection.VerticalCoordinate", prefix.c_str());
    attributeList.addAttribute(name, toString(mVerticalCoordinate));
    sprintf(name, "%sCrossSection.NC", prefix.c_str());
    attributeList.addAttribute(name, toString(mNC));
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for getting attribute values by their names.

    \param attributeName  The name of the attribute.
    \param attributeValue The value of the attribute (string).
*/

bool CrossSection::getAttributeValue(const char *attributeName, std::string &attributeValue) const {
  try {
    if (attributeName == nullptr)
      return false;
    if (mEarthShape.getAttributeValue(attributeName, attributeValue))
      return true;
    if (strcasecmp(attributeName, "NumberOfHorizontalPoints") == 0) {
      attributeValue = toString(mNumberOfHorizontalPoints);
      return true;
    }
    if (strcasecmp(attributeName, "BasicAngleOfTheInitialProductionDomain") == 0) {
      attributeValue = toString(mBasicAngleOfTheInitialProductionDomain);
      return true;
    }
    if (strcasecmp(attributeName, "SubdivisionsOfBasicAngle") == 0) {
      attributeValue = toString(mSubdivisionsOfBasicAngle);
      return true;
    }
    if (strcasecmp(attributeName, "LatitudeOfFirstGridPoint") == 0) {
      attributeValue = toString(mLatitudeOfFirstGridPoint);
      return true;
    }
    if (strcasecmp(attributeName, "LongitudeOfFirstGridPoint") == 0) {
      attributeValue = toString(mLongitudeOfFirstGridPoint);
      return true;
    }
    if (mScanningMode.getAttributeValue(attributeName, attributeValue))
      return true;
    if (strcasecmp(attributeName, "LatitudeOfLastGridPoint") == 0) {
      attributeValue = toString(mLatitudeOfLastGridPoint);
      return true;
    }
    if (strcasecmp(attributeName, "LongitudeOfLastGridPoint") == 0) {
      attributeValue = toString(mLongitudeOfLastGridPoint);
      return true;
    }
    if (strcasecmp(attributeName, "TypeOfHorizontalLine") == 0) {
      attributeValue = toString(mTypeOfHorizontalLine);
      return true;
    }
    if (strcasecmp(attributeName, "NumberOfVerticalPoints") == 0) {
      attributeValue = toString(mNumberOfVerticalPoints);
      return true;
    }
    if (strcasecmp(attributeName, "MeaningOfVerticalCoordinate") == 0) {
      attributeValue = toString(mMeaningOfVerticalCoordinate);
      return true;
    }
    if (strcasecmp(attributeName, "VerticalCoordinate") == 0) {
      attributeValue = toString(mVerticalCoordinate);
      return true;
    }
    if (strcasecmp(attributeName, "NC") == 0) {
      attributeValue = toString(mNC);
      return true;
    }
    return false;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for checking if the attribute value matches to the given value.

    \param attributeName  The name of the attribute.
    \param attributeValue The value of the attribute (string).
*/

bool CrossSection::hasAttributeValue(const char *attributeName, const char *attributeValue) const {
  try {
    if (attributeName == nullptr || attributeValue == nullptr)
      return false;
    if (mEarthShape.hasAttributeValue(attributeName, attributeValue))
      return true;
    if (strcasecmp(attributeName, "NumberOfHorizontalPoints") == 0 && strcasecmp(attributeValue, toString(mNumberOfHorizontalPoints).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "BasicAngleOfTheInitialProductionDomain") == 0 && strcasecmp(attributeValue, toString(mBasicAngleOfTheInitialProductionDomain).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "SubdivisionsOfBasicAngle") == 0 && strcasecmp(attributeValue, toString(mSubdivisionsOfBasicAngle).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "LatitudeOfFirstGridPoint") == 0 && strcasecmp(attributeValue, toString(mLatitudeOfFirstGridPoint).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "LongitudeOfFirstGridPoint") == 0 && strcasecmp(attributeValue, toString(mLongitudeOfFirstGridPoint).c_str()) == 0)
      return true;
    if (mScanningMode.hasAttributeValue(attributeName, attributeValue))
      return true;
    if (strcasecmp(attributeName, "LatitudeOfLastGridPoint") == 0 && strcasecmp(attributeValue, toString(mLatitudeOfLastGridPoint).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "LongitudeOfLastGridPoint") == 0 && strcasecmp(attributeValue, toString(mLongitudeOfLastGridPoint).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "TypeOfHorizontalLine") == 0 && strcasecmp(attributeValue, toString(mTypeOfHorizontalLine).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "NumberOfVerticalPoints") == 0 && strcasecmp(attributeValue, toString(mNumberOfVerticalPoints).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "MeaningOfVerticalCoordinate") == 0 && strcasecmp(attributeValue, toString(mMeaningOfVerticalCoordinate).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "VerticalCoordinate") == 0 && strcasecmp(attributeValue, toString(mVerticalCoordinate).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "NC") == 0 && strcasecmp(attributeValue, toString(mNC).c_str()) == 0)
      return true;
    return false;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method prints the content of the current object into the given stream.

    \param ostream      The output stream.
    \param level        The print level (used when printing multi-level structures).
    \param optionFlags  The printing options expressed in flag-bits.
*/

void CrossSection::print(std::ostream &stream, uint level, uint optionFlags) const {
  try {
    stream << space(level) << "CrossSection\n";
    mEarthShape.print(stream, level + 1, optionFlags);
    stream << space(level) << "- NumberOfHorizontalPoints = " << toString(mNumberOfHorizontalPoints) << "\n";
    stream << space(level) << "- BasicAngleOfTheInitialProductionDomain = " << toString(mBasicAngleOfTheInitialProductionDomain) << "\n";
    stream << space(level) << "- SubdivisionsOfBasicAngle = " << toString(mSubdivisionsOfBasicAngle) << "\n";
    stream << space(level) << "- LatitudeOfFirstGridPoint = " << toString(mLatitudeOfFirstGridPoint) << "\n";
    stream << space(level) << "- LongitudeOfFirstGridPoint = " << toString(mLongitudeOfFirstGridPoint) << "\n";
    mScanningMode.print(stream, level + 1, optionFlags);
    stream << space(level) << "- LatitudeOfLastGridPoint = " << toString(mLatitudeOfLastGridPoint) << "\n";
    stream << space(level) << "- LongitudeOfLastGridPoint = " << toString(mLongitudeOfLastGridPoint) << "\n";
    stream << space(level) << "- TypeOfHorizontalLine = " << toString(mTypeOfHorizontalLine) << "\n";
    stream << space(level) << "- NumberOfVerticalPoints = " << toString(mNumberOfVerticalPoints) << "\n";
    stream << space(level) << "- MeaningOfVerticalCoordinate = " << toString(mMeaningOfVerticalCoordinate) << "\n";
    stream << space(level) << "- VerticalCoordinate = " << toString(mVerticalCoordinate) << "\n";
    stream << space(level) << "- NC = " << toString(mNC) << "\n";
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method counts the hash value of the current object. */

T::Hash CrossSection::countHash() const {
  try {
    std::size_t seed = 0;
    if (mNumberOfHorizontalPoints)
      Fmi::hash_merge(seed, *mNumberOfHorizontalPoints);
    // if (mBasicAngleOfTheInitialProductionDomain) Fmi::hash_merge(seed,*mBasicAngleOfTheInitialProductionDomain);
    // if (mSubdivisionsOfBasicAngle) Fmi::hash_merge(seed,*mSubdivisionsOfBasicAngle);
    if (mLatitudeOfFirstGridPoint)
      Fmi::hash_merge(seed, *mLatitudeOfFirstGridPoint);
    if (mLongitudeOfFirstGridPoint)
      Fmi::hash_merge(seed, *mLongitudeOfFirstGridPoint);
    // if (mLatitudeOfLastGridPoint) Fmi::hash_merge(seed,*mLatitudeOfLastGridPoint);
    // if (mLongitudeOfLastGridPoint) Fmi::hash_merge(seed,*mLongitudeOfLastGridPoint);
    if (mTypeOfHorizontalLine)
      Fmi::hash_merge(seed, *mTypeOfHorizontalLine);
    if (mNumberOfVerticalPoints)
      Fmi::hash_merge(seed, *mNumberOfVerticalPoints);
    if (mMeaningOfVerticalCoordinate)
      Fmi::hash_merge(seed, *mMeaningOfVerticalCoordinate);
    if (mVerticalCoordinate)
      Fmi::hash_merge(seed, *mVerticalCoordinate);
    if (mNC)
      Fmi::hash_merge(seed, *mNC);
    return seed;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method return the template number of the current class. */

uint CrossSection::getTemplateNumber() const {
  return 1000;
}

GridDefinition *CrossSection::createGridDefinition() const {
  try {
    return static_cast<GridDefinition *>(new CrossSection(*this));
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the pointer to the {@link mEarthShape} attribute. */

EarthShapeSettings *CrossSection::getEarthShape() const {
  try {
    return static_cast<EarthShapeSettings *>(&mEarthShape);
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mNumberOfHorizontalPoints} attribute. */

const T::UInt32_opt &CrossSection::getNumberOfHorizontalPoints() const {
  try {
    return mNumberOfHorizontalPoints;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mBasicAngleOfTheInitialProductionDomain} attribute. */

const T::UInt32_opt &CrossSection::getBasicAngleOfTheInitialProductionDomain() const {
  try {
    return mBasicAngleOfTheInitialProductionDomain;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mSubdivisionsOfBasicAngle} attribute. */

const T::UInt32_opt &CrossSection::getSubdivisionsOfBasicAngle() const {
  try {
    return mSubdivisionsOfBasicAngle;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mLatitudeOfFirstGridPoint} attribute. */

const T::Int32_opt &CrossSection::getLatitudeOfFirstGridPoint() const {
  try {
    return mLatitudeOfFirstGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mLongitudeOfFirstGridPoint} attribute. */

const T::UInt32_opt &CrossSection::getLongitudeOfFirstGridPoint() const {
  try {
    return mLongitudeOfFirstGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the pointer to the {@link mScanningMode} attribute. */

ScanningModeSettings *CrossSection::getScanningMode() const {
  try {
    return static_cast<ScanningModeSettings *>(&mScanningMode);
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mLatitudeOfLastGridPoint} attribute. */

const T::Int32_opt &CrossSection::getLatitudeOfLastGridPoint() const {
  try {
    return mLatitudeOfLastGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mLongitudeOfLastGridPoint} attribute. */

const T::UInt32_opt &CrossSection::getLongitudeOfLastGridPoint() const {
  try {
    return mLongitudeOfLastGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mTypeOfHorizontalLine} attribute. */

const T::UInt8_opt &CrossSection::getTypeOfHorizontalLine() const {
  try {
    return mTypeOfHorizontalLine;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mNumberOfVerticalPoints} attribute. */

const T::UInt16_opt &CrossSection::getNumberOfVerticalPoints() const {
  try {
    return mNumberOfVerticalPoints;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mMeaningOfVerticalCoordinate} attribute. */

const T::UInt8_opt &CrossSection::getMeaningOfVerticalCoordinate() const {
  try {
    return mMeaningOfVerticalCoordinate;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mVerticalCoordinate} attribute. */

const T::UInt8_opt &CrossSection::getVerticalCoordinate() const {
  try {
    return mVerticalCoordinate;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mNC} attribute. */

const T::UInt16_opt &CrossSection::getNC() const {
  try {
    return mNC;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setEarthShape(EarthShapeSettings &earthShape) {
  try {
    mEarthShape = earthShape;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setNumberOfHorizontalPoints(T::UInt32_opt numberOfHorizontalPoints) {
  try {
    mNumberOfHorizontalPoints = numberOfHorizontalPoints;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setBasicAngleOfTheInitialProductionDomain(T::UInt32_opt basicAngleOfTheInitialProductionDomain) {
  try {
    mBasicAngleOfTheInitialProductionDomain = basicAngleOfTheInitialProductionDomain;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setSubdivisionsOfBasicAngle(T::UInt32_opt subdivisionsOfBasicAngle) {
  try {
    mSubdivisionsOfBasicAngle = subdivisionsOfBasicAngle;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setLatitudeOfFirstGridPoint(T::Int32_opt latitudeOfFirstGridPoint) {
  try {
    mLatitudeOfFirstGridPoint = latitudeOfFirstGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setLongitudeOfFirstGridPoint(T::UInt32_opt longitudeOfFirstGridPoint) {
  try {
    mLongitudeOfFirstGridPoint = longitudeOfFirstGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setScanningMode(ScanningModeSettings &scanningMode) {
  try {
    mScanningMode = scanningMode;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setLatitudeOfLastGridPoint(T::Int32_opt latitudeOfLastGridPoint) {
  try {
    mLatitudeOfLastGridPoint = latitudeOfLastGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setLongitudeOfLastGridPoint(T::UInt32_opt longitudeOfLastGridPoint) {
  try {
    mLongitudeOfLastGridPoint = longitudeOfLastGridPoint;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setTypeOfHorizontalLine(T::UInt8_opt typeOfHorizontalLine) {
  try {
    mTypeOfHorizontalLine = typeOfHorizontalLine;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setNumberOfVerticalPoints(T::UInt16_opt numberOfVerticalPoints) {
  try {
    mNumberOfVerticalPoints = numberOfVerticalPoints;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setMeaningOfVerticalCoordinate(T::UInt8_opt meaningOfVerticalCoordinate) {
  try {
    mMeaningOfVerticalCoordinate = meaningOfVerticalCoordinate;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setVerticalCoordinate(T::UInt8_opt verticalCoordinate) {
  try {
    mVerticalCoordinate = verticalCoordinate;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void CrossSection::setNC(T::UInt16_opt nC) {
  try {
    mNC = nC;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

} // namespace GRIB2
} // namespace SmartMet
