CREATE_CLASS_DEFINITIONS = ../../../php/createClassDefinitions_grib2.php
T_DIR = /usr/share/eccodes/definitions/grib2
T_TARGET_DIR = .

H_FILES = \
	EarthShapeSettings.h \
	ScanningModeSettings.h \
	RotationSettings.h \
	GridSettings.h \
	PostprocSettings.h \
	ResolutionSettings.h \
	StretchingSettings.h \
	LatLonSettings.h \
	VariableLatLonSettings.h \
	GaussianSettings.h \
	SphericalHarmonicSettings.h \
	LatLon.h \
	RotatedLatLon.h \
	StretchedLatLon.h \
	StretchedRotatedLatLon.h \
	VariableResolutionLatLon.h \
	VariableResolutionRotatedLatLon.h \
	Mercator.h \
	TransverseMercator.h \
	PolarStereographic.h \
	LambertConformal.h \
	Albers.h \
	Gaussian.h \
	RotatedGaussian.h \
	StretchedGaussian.h \
	StretchedRotatedGaussian.h \
	SphericalHarmonic.h \
	RotatedSphericalHarmonic.h \
	StretchedSphericalHarmonic.h \
	StretchedRotatedSphericalHarmonic.h \
	SpaceView.h \
	Triangular.h \
	Unstructured.h \
	EquatorialAzimuthalEquidistant.h \
	AzimuthRange.h \
	IrregularLatLon.h \
	LambertAzimuthalEqualArea.h \
	CrossSection.h \
	Hovmoller.h \
	TimeSection.h \
	CategoricalSettings.h \
	DerivedSettings.h \
	EpsSettings.h \
	HorizontalSettings.h \
	ParameterAerosolSettings.h \
	ParameterAerosolOpticalSettings.h \
	ParameterChemicalSettings.h \
	ParameterSettings.h \
	ParameterPartitionSettings.h \
	PercentileSettings.h \
  PointInTimeSettings.h \
  ProbabilitySettings.h \
  RectangularClusterSettings.h \
  ReforecastSettings.h \
  StatisticalSettings.h \
  NormalProduct.h \
  EnsembleForecast.h \
  EnsembleDerivedForecast.h \
  EnsembleClusterDerivedForecast.h \
  ProbabilityForecast.h \
  PercentileForecast.h \
  ForecastError.h \
  AggregateForecast.h \
  TimeIntervalProbabilityForecast.h \
  TimeIntervalPercentileForecast.h \
  TimeIntervalEnsembleForecast.h \
  TimeIntervalEnsembleDerivedForecast.h \
  TimeIntervalEnsembleClusterDerivedForecast.h \
  TimeIntervalAggregateForecast.h \
  DeprecatedSatelliteProduct.h \
  AuxiliarySatelliteProduct.h \
  SatelliteProduct.h \
  SimulatedSatelliteProduct.h \
  SimulatedSatelliteEnsembleProduct.h \
  TimeIntervalSimulatedSatelliteEnsembleProduct.h \
  AtmosphericChemicalProduct.h \
  AtmosphericChemicalEnsembleProduct.h \
  AggregateAtmosphericChemicalProduct.h \
  TimeIntervalAtmosphericChemicalEnsembleProduct.h \
  AerosolEnsembleProduct.h \
  AggregateAerosolProduct.h \
  TimeIntervalAerosolEnsembleProduct.h \
  AerosolOpticalPropertiesProduct.h \
  CategoricalForecast.h \
  PartitionedProduct.h \
  PartitionedEnsembleProduct.h \
  EnsembleReforecast.h \
  TimeIntervalEnsembleReforecast.h \
  Product_49.h \
  Product_55.h \
  Product_56.h \
  Product_57.h \
  Product_58.h \
  Product_59.h \
  Product_67.h \
  Product_68.h \
  Product_70.h \
  Product_71.h \
  Product_72.h \
  Product_73.h \
  TimeIntervalCategoricalForecast.h \
  CharacterStringProduct.h \
  CrossSectionProduct.h \
  ProcessedCrossSectionProduct.h \
  AreaProcessedCrossSectionProduct.h \
  HovmollerProduct.h \
  ProcessedHovmollerProduct.h \
  OriginalValuesSettings.h \
  PackingSettings.h \
  SecondOrderSettings.h \
  GridDataRepresentation.h \
  MatrixDataRepresentation.h \
  ComplexGridDataRepresentation.h \
  ComplexDifferenceGridDataRepresentation.h \
  FloatingPointGridDataRepresentation.h \
  PreprocessedGridDataRepresentation.h \
  JpegGridDataRepresentation.h \
  PngGridDataRepresentation.h \
  SpectralGridDataRepresentation.h \
  SpectralDataRepresentation.h \
  SphericalHarmonicsDataRepresentation.h \
  LogarithmicGridDataRepresentation.h \
  ComplexSphericalHarmonicsDataRepresentation.h \
  ComplexPackingSettings.h \
  GridData.h \
  MatrixData.h \
  ComplexGridData.h \
  ComplexDifferenceGridData.h \
  FloatingPointGridData.h \
  PreprocessedGridData.h \
  JpegGridData.h \
  PngGridData.h \
  SpectralGridData.h \
  SpectralData.h \
  SphericalHarmonicsData.h \
  LogarithmicGridData.h \
  ComplexSphericalHarmonicsData.h

CPP_FILES = \
	EarthShapeSettings.cpp \
	ScanningModeSettings.cpp \
	RotationSettings.cpp \
	GridSettings.cpp \
	PostprocSettings.cpp \
	ResolutionSettings.cpp \
	StretchingSettings.cpp \
	LatLonSettings.cpp \
	VariableLatLonSettings.cpp \
	GaussianSettings.cpp \
	SphericalHarmonicSettings.cpp \
	LatLon.cpp \
	RotatedLatLon.cpp \
	StretchedLatLon.cpp \
	StretchedRotatedLatLon.cpp \
	VariableResolutionLatLon.cpp \
	VariableResolutionRotatedLatLon.cpp \
	Mercator.cpp \
	TransverseMercator.cpp \
	PolarStereographic.cpp \
	LambertConformal.cpp \
	Albers.cpp \
	Gaussian.cpp \
	RotatedGaussian.cpp \
	StretchedGaussian.cpp \
	StretchedRotatedGaussian.cpp \
	SphericalHarmonic.cpp \
	RotatedSphericalHarmonic.cpp \
	StretchedSphericalHarmonic.cpp \
	StretchedRotatedSphericalHarmonic.cpp \
	SpaceView.cpp \
	Triangular.cpp \
	Unstructured.cpp \
	EquatorialAzimuthalEquidistant.cpp \
	AzimuthRange.cpp \
	IrregularLatLon.cpp \
	LambertAzimuthalEqualArea.cpp \
	CrossSection.cpp \
	Hovmoller.cpp \
	TimeSection.cpp \
	CategoricalSettings.cpp \
	DerivedSettings.cpp \
	EpsSettings.cpp \
	HorizontalSettings.cpp \
	ParameterAerosolSettings.cpp \
	ParameterAerosolOpticalSettings.cpp \
	ParameterChemicalSettings.cpp \
	ParameterSettings.cpp \
	ParameterPartitionSettings.cpp \
	PercentileSettings.cpp \
  PointInTimeSettings.cpp \
  ProbabilitySettings.cpp \
  RectangularClusterSettings.cpp \
  ReforecastSettings.cpp \
  StatisticalSettings.cpp \
  NormalProduct.cpp \
  EnsembleForecast.cpp \
  EnsembleDerivedForecast.cpp \
  EnsembleClusterDerivedForecast.cpp \
  ProbabilityForecast.cpp \
  PercentileForecast.cpp \
  ForecastError.cpp \
  AggregateForecast.cpp \
  TimeIntervalProbabilityForecast.cpp \
  TimeIntervalPercentileForecast.cpp \
  TimeIntervalEnsembleForecast.cpp \
  TimeIntervalEnsembleDerivedForecast.cpp \
  TimeIntervalEnsembleClusterDerivedForecast.cpp \
  TimeIntervalAggregateForecast.cpp \
  DeprecatedSatelliteProduct.cpp \
  AuxiliarySatelliteProduct.cpp \
  SatelliteProduct.cpp \
  SimulatedSatelliteProduct.cpp \
  SimulatedSatelliteEnsembleProduct.cpp \
  TimeIntervalSimulatedSatelliteEnsembleProduct.cpp \
  AtmosphericChemicalProduct.cpp \
  AtmosphericChemicalEnsembleProduct.cpp \
  AggregateAtmosphericChemicalProduct.cpp \
  TimeIntervalAtmosphericChemicalEnsembleProduct.cpp \
  AerosolEnsembleProduct.cpp \
  AggregateAerosolProduct.cpp \
  TimeIntervalAerosolEnsembleProduct.cpp \
  AerosolOpticalPropertiesProduct.cpp \
  CategoricalForecast.cpp \
  PartitionedProduct.cpp \
  PartitionedEnsembleProduct.cpp \
  EnsembleReforecast.cpp \
  TimeIntervalEnsembleReforecast.cpp \
  Product_49.cpp \
  Product_55.cpp \
  Product_56.cpp \
  Product_57.cpp \
  Product_58.cpp \
  Product_59.cpp \
  Product_67.cpp \
  Product_68.cpp \
  Product_70.cpp \
  Product_71.cpp \
  Product_72.cpp \
  Product_73.cpp \
  TimeIntervalCategoricalForecast.cpp \
  CharacterStringProduct.cpp \
  CrossSectionProduct.cpp \
  ProcessedCrossSectionProduct.cpp \
  AreaProcessedCrossSectionProduct.cpp \
  HovmollerProduct.cpp \
  ProcessedHovmollerProduct.cpp \
  OriginalValuesSettings.cpp \
  PackingSettings.cpp \
  SecondOrderSettings.cpp \
  GridDataRepresentation.cpp \
  MatrixDataRepresentation.cpp \
  ComplexGridDataRepresentation.cpp \
  ComplexDifferenceGridDataRepresentation.cpp \
  FloatingPointGridDataRepresentation.cpp \
  PreprocessedGridDataRepresentation.cpp \
  JpegGridDataRepresentation.cpp \
  PngGridDataRepresentation.cpp \
  SpectralGridDataRepresentation.cpp \
  SpectralDataRepresentation.cpp \
  SphericalHarmonicsDataRepresentation.cpp \
  LogarithmicGridDataRepresentation.cpp \
  ComplexSphericalHarmonicsDataRepresentation.cpp \
  ComplexPackingSettings.cpp \
  GridData.cpp \
  MatrixData.cpp \
  ComplexGridData.cpp \
  ComplexDifferenceGridData.cpp \
  FloatingPointGridData.cpp \
  PreprocessedGridData.cpp \
  JpegGridData.cpp \
  PngGridData.cpp \
  SpectralGridData.cpp \
  SpectralData.cpp \
  SphericalHarmonicsData.cpp \
  LogarithmicGridData.cpp \
  ComplexSphericalHarmonicsData.cpp


all: definitions

definitions: $(H_FILES)

clean:
	rm -f $(H_FILES)
	rm -f $(CPP_FILES)


EarthShapeSettings.h: $(T_DIR)/template.3.shape_of_the_earth.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.shape_of_the_earth.def $(T_TARGET_DIR)

ScanningModeSettings.h: $(T_DIR)/template.3.scanning_mode.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.scanning_mode.def $(T_TARGET_DIR)

RotationSettings.h: $(T_DIR)/template.3.rotation.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.rotation.def $(T_TARGET_DIR)

GridSettings.h: $(T_DIR)/template.3.grid.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.grid.def $(T_TARGET_DIR)

ResolutionSettings.h: $(T_DIR)/template.3.resolution_flags.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.resolution_flags.def $(T_TARGET_DIR)

StretchingSettings.h: $(T_DIR)/template.3.stretching.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.stretching.def $(T_TARGET_DIR)

LatLonSettings.h: $(T_DIR)/template.3.latlon.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.latlon.def $(T_TARGET_DIR)

VariableLatLonSettings.h: $(T_DIR)/template.3.latlon_vares.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.latlon_vares.def $(T_TARGET_DIR)

GaussianSettings.h: $(T_DIR)/template.3.gaussian.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.gaussian.def $(T_TARGET_DIR)

SphericalHarmonicSettings.h: $(T_DIR)/template.3.spherical_harmonics.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.spherical_harmonics.def $(T_TARGET_DIR)

LatLon.h: $(T_DIR)/template.3.0.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.0.def $(T_TARGET_DIR)

RotatedLatLon.h: $(T_DIR)/template.3.1.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.1.def $(T_TARGET_DIR)

StretchedLatLon.h: $(T_DIR)/template.3.2.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.2.def $(T_TARGET_DIR)

StretchedRotatedLatLon.h: $(T_DIR)/template.3.3.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.3.def $(T_TARGET_DIR)

VariableResolutionLatLon.h: $(T_DIR)/template.3.4.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.4.def $(T_TARGET_DIR)

VariableResolutionRotatedLatLon.h: $(T_DIR)/template.3.5.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.5.def $(T_TARGET_DIR)

Mercator.h: $(T_DIR)/template.3.10.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.10.def $(T_TARGET_DIR)

TransverseMercator.h: $(T_DIR)/template.3.12.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.12.def $(T_TARGET_DIR)

PolarStereographic.h: $(T_DIR)/template.3.20.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.20.def $(T_TARGET_DIR)

LambertConformal.h: $(T_DIR)/template.3.30.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.30.def $(T_TARGET_DIR)

Albers.h: $(T_DIR)/template.3.31.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.31.def $(T_TARGET_DIR)

Gaussian.h: $(T_DIR)/template.3.40.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.40.def $(T_TARGET_DIR)

RotatedGaussian.h: $(T_DIR)/template.3.41.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.41.def $(T_TARGET_DIR)

StretchedGaussian.h: $(T_DIR)/template.3.42.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.42.def $(T_TARGET_DIR)

StretchedRotatedGaussian.h: $(T_DIR)/template.3.43.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.43.def $(T_TARGET_DIR)

SphericalHarmonic.h: $(T_DIR)/template.3.50.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.50.def $(T_TARGET_DIR)

RotatedSphericalHarmonic.h: $(T_DIR)/template.3.51.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.51.def $(T_TARGET_DIR)

StretchedSphericalHarmonic.h: $(T_DIR)/template.3.52.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.52.def $(T_TARGET_DIR)

StretchedRotatedSphericalHarmonic.h: $(T_DIR)/template.3.53.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.53.def $(T_TARGET_DIR)

SpaceView.h: $(T_DIR)/template.3.90.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.90.def $(T_TARGET_DIR)

Triangular.h: $(T_DIR)/template.3.100.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.100.def $(T_TARGET_DIR)

Unstructured.h: $(T_DIR)/template.3.101.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.101.def $(T_TARGET_DIR)

EquatorialAzimuthalEquidistant.h: $(T_DIR)/template.3.110.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.110.def $(T_TARGET_DIR)

AzimuthRange.h: $(T_DIR)/template.3.120.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.120.def $(T_TARGET_DIR)

IrregularLatLon.h: $(T_DIR)/template.3.130.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.130.def $(T_TARGET_DIR)

LambertAzimuthalEqualArea.h: $(T_DIR)/template.3.140.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.140.def $(T_TARGET_DIR)

CrossSection.h: $(T_DIR)/template.3.1000.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.1000.def $(T_TARGET_DIR)

Hovmoller.h: $(T_DIR)/template.3.1100.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.1100.def $(T_TARGET_DIR)

TimeSection.h: $(T_DIR)/template.3.1200.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.3.1200.def $(T_TARGET_DIR)



CategoricalSettings.h: $(T_DIR)/template.4.categorical.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.categorical.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.circular_cluster.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.circular_cluster.def $(T_TARGET_DIR)

DerivedSettings.h: $(T_DIR)/template.4.derived.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.derived.def $(T_TARGET_DIR)

EpsSettings.h: $(T_DIR)/template.4.eps.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.eps.def $(T_TARGET_DIR)

HorizontalSettings.h: $(T_DIR)/template.4.horizontal.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.horizontal.def $(T_TARGET_DIR)

ParameterAerosolSettings.h: $(T_DIR)/template.4.parameter_aerosol.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter_aerosol.def $(T_TARGET_DIR)

ParameterAerosolOpticalSettings.h: $(T_DIR)/template.4.parameter_aerosol_optical.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter_aerosol_optical.def $(T_TARGET_DIR)

ParameterChemicalSettings.h: $(T_DIR)/template.4.parameter_chemical.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter_chemical.def $(T_TARGET_DIR)

ParameterSettings.h: $(T_DIR)/template.4.parameter.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter.def $(T_TARGET_DIR)

ParameterPartitionSettings.h: $(T_DIR)/template.4.parameter_partition.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter_partition.def $(T_TARGET_DIR)

PercentileSettings.h: $(T_DIR)/template.4.percentile.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.percentile.def $(T_TARGET_DIR)

PointInTimeSettings.h: $(T_DIR)/template.4.point_in_time.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.point_in_time.def $(T_TARGET_DIR)

ProbabilitySettings.h: $(T_DIR)/template.4.probability.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.probability.def $(T_TARGET_DIR)

PostprocSettings.h: $(T_DIR)/template.4.eps.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.parameter_postproc.def $(T_TARGET_DIR)

RectangularClusterSettings.h: $(T_DIR)/template.4.rectangular_cluster.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.rectangular_cluster.def $(T_TARGET_DIR)

ReforecastSettings.h: $(T_DIR)/template.4.reforecast.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.reforecast.def $(T_TARGET_DIR)

StatisticalSettings.h: $(T_DIR)/template.4.statistical.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.statistical.def $(T_TARGET_DIR)

NormalProduct.h: $(T_DIR)/template.4.0.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.0.def $(T_TARGET_DIR)

EnsembleForecast.h: $(T_DIR)/template.4.1.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1.def $(T_TARGET_DIR)

EnsembleDerivedForecast.h: $(T_DIR)/template.4.2.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.2.def $(T_TARGET_DIR)

EnsembleClusterDerivedForecast.h: $(T_DIR)/template.4.3.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.3.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.4.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.4.def  $(T_TARGET_DIR)

ProbabilityForecast.h: $(T_DIR)/template.4.5.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.5.def $(T_TARGET_DIR)

PercentileForecast.h: $(T_DIR)/template.4.6.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.6.def $(T_TARGET_DIR)


ForecastError.h: $(T_DIR)/template.4.7.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.7.def $(T_TARGET_DIR)

AggregateForecast.h: $(T_DIR)/template.4.8.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.8.def $(T_TARGET_DIR)

TimeIntervalProbabilityForecast.h: $(T_DIR)/template.4.9.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.9.def $(T_TARGET_DIR)

TimeIntervalPercentileForecast.h: $(T_DIR)/template.4.10.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.10.def $(T_TARGET_DIR)

TimeIntervalEnsembleForecast.h: $(T_DIR)/template.4.11.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.11.def $(T_TARGET_DIR)

TimeIntervalEnsembleDerivedForecast.h: $(T_DIR)/template.4.12.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.12.def $(T_TARGET_DIR)

TimeIntervalEnsembleClusterDerivedForecast.h: $(T_DIR)/template.4.13.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.13.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.14.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.14.def   $(T_TARGET_DIR)

TimeIntervalAggregateForecast.h: $(T_DIR)/template.4.15.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.15.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.20.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.20.def $(T_TARGET_DIR)

DeprecatedSatelliteProduct.h: $(T_DIR)/template.4.30.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.30.def $(T_TARGET_DIR)

AuxiliarySatelliteProduct.h: $(T_DIR)/template.4.311.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.311.def $(T_TARGET_DIR)

SatelliteProduct.h: $(T_DIR)/template.4.31.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.31.def $(T_TARGET_DIR)

SimulatedSatelliteProduct.h: $(T_DIR)/template.4.32.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.32.def $(T_TARGET_DIR)

SimulatedSatelliteEnsembleProduct.h: $(T_DIR)/template.4.33.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.33.def $(T_TARGET_DIR)

TimeIntervalSimulatedSatelliteEnsembleProduct.h: $(T_DIR)/template.4.34.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.34.def $(T_TARGET_DIR)

AtmosphericChemicalProduct.h: $(T_DIR)/template.4.40.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.40.def $(T_TARGET_DIR)

AtmosphericChemicalEnsembleProduct.h: $(T_DIR)/template.4.41.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.41.def $(T_TARGET_DIR)

AggregateAtmosphericChemicalProduct.h: $(T_DIR)/template.4.42.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.42.def $(T_TARGET_DIR)

TimeIntervalAtmosphericChemicalEnsembleProduct.h: $(T_DIR)/template.4.43.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.43.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.44.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.44.def $(T_TARGET_DIR)

AerosolEnsembleProduct.h: $(T_DIR)/template.4.45.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.45.def $(T_TARGET_DIR)

AggregateAerosolProduct.h: $(T_DIR)/template.4.46.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.46.def $(T_TARGET_DIR)

TimeIntervalAerosolEnsembleProduct.h: $(T_DIR)/template.4.47.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.47.def $(T_TARGET_DIR)

AerosolOpticalPropertiesProduct.h: $(T_DIR)/template.4.48.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.48.def $(T_TARGET_DIR)

CategoricalForecast.h: $(T_DIR)/template.4.51.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.51.def $(T_TARGET_DIR)

PartitionedProduct.h: $(T_DIR)/template.4.53.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.53.def $(T_TARGET_DIR)

PartitionedEnsembleProduct.h: $(T_DIR)/template.4.54.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.54.def $(T_TARGET_DIR)

EnsembleReforecast.h: $(T_DIR)/template.4.60.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.60.def $(T_TARGET_DIR)

TimeIntervalEnsembleReforecast.h: $(T_DIR)/template.4.61.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.61.def $(T_TARGET_DIR)

Product_49.h: $(T_DIR)/template.4.49.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.49.def $(T_TARGET_DIR)

Product_55.h: $(T_DIR)/template.4.55.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.55.def $(T_TARGET_DIR)

Product_56.h: $(T_DIR)/template.4.56.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.56.def $(T_TARGET_DIR)

Product_57.h: $(T_DIR)/template.4.57.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.57.def $(T_TARGET_DIR)

Product_58.h: $(T_DIR)/template.4.58.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.58.def $(T_TARGET_DIR)

Product_59.h: $(T_DIR)/template.4.59.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.59.def $(T_TARGET_DIR)

Product_67.h: $(T_DIR)/template.4.67.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.67.def $(T_TARGET_DIR)

Product_68.h: $(T_DIR)/template.4.68.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.68.def $(T_TARGET_DIR)

Product_70.h: $(T_DIR)/template.4.70.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.70.def $(T_TARGET_DIR)

Product_71.h: $(T_DIR)/template.4.71.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.71.def $(T_TARGET_DIR)

Product_72.h: $(T_DIR)/template.4.72.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.72.def $(T_TARGET_DIR)

Product_73.h: $(T_DIR)/template.4.73.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.73.def $(T_TARGET_DIR)

TimeIntervalCategoricalForecast.h: $(T_DIR)/template.4.91.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.91.def $(T_TARGET_DIR)

CharacterStringProduct.h: $(T_DIR)/template.4.254.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.254.def $(T_TARGET_DIR)

CrossSectionProduct.h: $(T_DIR)/template.4.1000.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1000.def $(T_TARGET_DIR)

ProcessedCrossSectionProduct.h: $(T_DIR)/template.4.1001.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1001.def $(T_TARGET_DIR)

AreaProcessedCrossSectionProduct.h: $(T_DIR)/template.4.1002.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1002.def $(T_TARGET_DIR)

HovmollerProduct.h: $(T_DIR)/template.4.1100.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1100.def $(T_TARGET_DIR)

ProcessedHovmollerProduct.h: $(T_DIR)/template.4.1101.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.1101.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.2000.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.2000.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.40033.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.40033.def $(T_TARGET_DIR)

#: $(T_DIR)/template.4.40034.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.4.40034.def $(T_TARGET_DIR)



OriginalValuesSettings.h: $(T_DIR)/template.5.original_values.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.original_values.def $(T_TARGET_DIR)

PackingSettings.h: $(T_DIR)/template.5.packing.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.packing.def $(T_TARGET_DIR)

SecondOrderSettings.h: $(T_DIR)/template.5.second_order.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.second_order.def $(T_TARGET_DIR)

GridDataRepresentation.h: $(T_DIR)/template.5.0.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.0.def $(T_TARGET_DIR)

MatrixDataRepresentation.h: $(T_DIR)/template.5.1.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.1.def $(T_TARGET_DIR)

ComplexGridDataRepresentation.h: $(T_DIR)/template.5.2.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.2.def $(T_TARGET_DIR)

ComplexDifferenceGridDataRepresentation.h: $(T_DIR)/template.5.3.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.3.def $(T_TARGET_DIR)

FloatingPointGridDataRepresentation.h: $(T_DIR)/template.5.4.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.4.def $(T_TARGET_DIR)

PreprocessedGridDataRepresentation.h: $(T_DIR)/template.5.6.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.6.def $(T_TARGET_DIR)

JpegGridDataRepresentation.h: $(T_DIR)/template.5.40.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.40.def $(T_TARGET_DIR)

PngGridDataRepresentation.h: $(T_DIR)/template.5.41.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.41.def $(T_TARGET_DIR)

SpectralGridDataRepresentation.h: $(T_DIR)/template.5.42.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.42.def $(T_TARGET_DIR)

SpectralDataRepresentation.h: $(T_DIR)/template.5.50.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.50.def $(T_TARGET_DIR)

SphericalHarmonicsDataRepresentation.h: $(T_DIR)/template.5.51.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.51.def $(T_TARGET_DIR)

LogarithmicGridDataRepresentation.h: $(T_DIR)/template.5.61.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.61.def $(T_TARGET_DIR)

#: $(T_DIR)/template.5.40000.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.40000.def $(T_TARGET_DIR)

#: $(T_DIR)/template.5.40010.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.40010.def $(T_TARGET_DIR)

ComplexSphericalHarmonicsDataRepresentation.h: $(T_DIR)/template.5.50000.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.50000.def $(T_TARGET_DIR)

#: $(T_DIR)/template.5.50001.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.50001.def $(T_TARGET_DIR)

#: $(T_DIR)/template.5.50002.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.5.50002.def $(T_TARGET_DIR)



ComplexPackingSettings.h: $(T_DIR)/template.7.second_order.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.second_order.def $(T_TARGET_DIR)

#: $(T_DIR)/template.second_order.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.second_order.def $(T_TARGET_DIR)

GridData.h: $(T_DIR)/template.7.0.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.0.def $(T_TARGET_DIR)

MatrixData.h: $(T_DIR)/template.7.1.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.1.def $(T_TARGET_DIR)

ComplexGridData.h: $(T_DIR)/template.7.2.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.2.def $(T_TARGET_DIR)

ComplexDifferenceGridData.h: $(T_DIR)/template.7.3.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.3.def $(T_TARGET_DIR)

FloatingPointGridData.h: $(T_DIR)/template.7.4.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.4.def $(T_TARGET_DIR)

PreprocessedGridData.h: $(T_DIR)/template.7.6.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.6.def $(T_TARGET_DIR)

JpegGridData.h: $(T_DIR)/template.7.40.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.40.def $(T_TARGET_DIR)

PngGridData.h: $(T_DIR)/template.7.41.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.41.def $(T_TARGET_DIR)

SpectralGridData.h: $(T_DIR)/template.7.42.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.42.def $(T_TARGET_DIR)

SpectralData.h: $(T_DIR)/template.7.50.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.50.def $(T_TARGET_DIR)

SphericalHarmonicsData.h: $(T_DIR)/template.7.51.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.51.def $(T_TARGET_DIR)

LogarithmicGridData.h: $(T_DIR)/template.7.61.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.61.def $(T_TARGET_DIR)

ComplexSphericalHarmonicsData.h: $(T_DIR)/template.7.50000.def $(CREATE_CLASS_DEFINITIONS)
	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.50000.def $(T_TARGET_DIR)

#: $(T_DIR)/template.7.40000.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.40000.def $(T_TARGET_DIR)

#: $(T_DIR)/template.7.40010.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.40010.def $(T_TARGET_DIR)

#: $(T_DIR)/template.7.50001.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.50001.def $(T_TARGET_DIR)

#: $(T_DIR)/template.7.50002.def $(CREATE_CLASS_DEFINITIONS)
#	$(CREATE_CLASS_DEFINITIONS) $(T_DIR)/template.7.50002.def $(T_TARGET_DIR)

