// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'OriginalValuesSettingsImpl.*' files.
// ***********************************************************************

#include "grib2/definition/OriginalValuesSettings.h"
#include "common/Exception.h"
#include "common/GeneralDefinitions.h"
#include "common/GeneralFunctions.h"
#include <boost/functional/hash.hpp>
#include <iostream>

namespace SmartMet {
namespace GRIB2 {

/*! \brief The constructor of the class. */

OriginalValuesSettings::OriginalValuesSettings() {
  try {
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The destructor of the class. */

OriginalValuesSettings::~OriginalValuesSettings() {
  try {
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The method reads and initializes all data related to the current object.

        \param memoryReader  This object controls the access to the memory mapped file.
*/

void OriginalValuesSettings::read(MemoryReader &memoryReader) {
  try {
    mTypeOfOriginalFieldValues = memoryReader.read_UInt8_opt();
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The method is used for collecting the current class attributeList.

    \param prefix         The prefix of the each attributeList parameter.
    \param attributeList  The attributeList storage.
*/

void OriginalValuesSettings::getAttributeList(std::string prefix, T::AttributeList &attributeList) const {
  try {
    char name[300];
    sprintf(name, "%sOriginalValuesSettings.TypeOfOriginalFieldValues", prefix.c_str());
    attributeList.addAttribute(name, toString(mTypeOfOriginalFieldValues));
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The method prints the content of the current object into the given stream.

    \param ostream      The output stream.
    \param level        The print level (used when printing multi-level structures).
    \param optionFlags  The printing options expressed in flag-bits.
*/

void OriginalValuesSettings::print(std::ostream &stream, uint level, uint optionFlags) const {
  try {
    stream << space(level) << "OriginalValuesSettings\n";
    stream << space(level) << "- TypeOfOriginalFieldValues = " << toString(mTypeOfOriginalFieldValues) << "\n";
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The method counts the hash value of the current object. */

T::Hash OriginalValuesSettings::countHash() {
  try {
    std::size_t seed = 0;
    if (mTypeOfOriginalFieldValues)
      boost::hash_combine(seed, *mTypeOfOriginalFieldValues);
    return seed;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

/*! \brief The method returns the value of the {@link mTypeOfOriginalFieldValues} attribute. */

const T::UInt8_opt &OriginalValuesSettings::getTypeOfOriginalFieldValues() const {
  try {
    return mTypeOfOriginalFieldValues;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

void OriginalValuesSettings::setTypeOfOriginalFieldValues(T::UInt8_opt typeOfOriginalFieldValues) {
  try {
    mTypeOfOriginalFieldValues = typeOfOriginalFieldValues;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, "Operation failed!", NULL);
  }
}

} // namespace GRIB2
} // namespace SmartMet
