// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'ProbabilitySettingsImpl.*' files.
// ***********************************************************************

#include "ProbabilitySettings.h"
#include "../../common/GeneralDefinitions.h"
#include "../../common/GeneralFunctions.h"
#include <boost/functional/hash.hpp>
#include <iostream>
#include <macgyver/Exception.h>

namespace SmartMet {
namespace GRIB2 {

/*! \brief The constructor of the class. */

ProbabilitySettings::ProbabilitySettings() {
  try {
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The destructor of the class. */

ProbabilitySettings::~ProbabilitySettings() {
}

/*! \brief The method reads and initializes all data related to the current object.

        \param memoryReader  This object controls the access to the memory mapped file.
*/

void ProbabilitySettings::read(MemoryReader &memoryReader) {
  try {
    mForecastProbabilityNumber = memoryReader.read_UInt8_opt();
    mTotalNumberOfForecastProbabilities = memoryReader.read_UInt8_opt();
    mProbabilityType = memoryReader.read_UInt8_opt();
    mScaleFactorOfLowerLimit = memoryReader.read_Int8_opt();
    mScaledValueOfLowerLimit = memoryReader.read_Int32_opt();
    mScaleFactorOfUpperLimit = memoryReader.read_Int8_opt();
    mScaledValueOfUpperLimit = memoryReader.read_Int32_opt();
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method writes all data related to the current object.

        \param dataWriter  This object is used for writing the object data.
*/

void ProbabilitySettings::write(DataWriter &dataWriter) {
  try {
    dataWriter << mForecastProbabilityNumber;
    dataWriter << mTotalNumberOfForecastProbabilities;
    dataWriter << mProbabilityType;
    dataWriter << mScaleFactorOfLowerLimit;
    dataWriter << mScaledValueOfLowerLimit;
    dataWriter << mScaleFactorOfUpperLimit;
    dataWriter << mScaledValueOfUpperLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for collecting the current class attributeList.

    \param prefix         The prefix of the each attributeList parameter.
    \param attributeList  The attributeList storage.
*/

void ProbabilitySettings::getAttributeList(const std::string &prefix, T::AttributeList &attributeList) const {
  try {
    char name[300];
    sprintf(name, "%sProbabilitySettings.ForecastProbabilityNumber", prefix.c_str());
    attributeList.addAttribute(name, toString(mForecastProbabilityNumber));
    sprintf(name, "%sProbabilitySettings.TotalNumberOfForecastProbabilities", prefix.c_str());
    attributeList.addAttribute(name, toString(mTotalNumberOfForecastProbabilities));
    sprintf(name, "%sProbabilitySettings.ProbabilityType", prefix.c_str());
    attributeList.addAttribute(name, toString(mProbabilityType));
    sprintf(name, "%sProbabilitySettings.ScaleFactorOfLowerLimit", prefix.c_str());
    attributeList.addAttribute(name, toString(mScaleFactorOfLowerLimit));
    sprintf(name, "%sProbabilitySettings.ScaledValueOfLowerLimit", prefix.c_str());
    attributeList.addAttribute(name, toString(mScaledValueOfLowerLimit));
    sprintf(name, "%sProbabilitySettings.ScaleFactorOfUpperLimit", prefix.c_str());
    attributeList.addAttribute(name, toString(mScaleFactorOfUpperLimit));
    sprintf(name, "%sProbabilitySettings.ScaledValueOfUpperLimit", prefix.c_str());
    attributeList.addAttribute(name, toString(mScaledValueOfUpperLimit));
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for getting attribute values by their names.

    \param attributeName  The name of the attribute.
    \param attributeValue The value of the attribute (string).
*/

bool ProbabilitySettings::getAttributeValue(const char *attributeName, std::string &attributeValue) const {
  try {
    if (attributeName == nullptr)
      return false;
    if (strcasecmp(attributeName, "ForecastProbabilityNumber") == 0) {
      attributeValue = toString(mForecastProbabilityNumber);
      return true;
    }
    if (strcasecmp(attributeName, "TotalNumberOfForecastProbabilities") == 0) {
      attributeValue = toString(mTotalNumberOfForecastProbabilities);
      return true;
    }
    if (strcasecmp(attributeName, "ProbabilityType") == 0) {
      attributeValue = toString(mProbabilityType);
      return true;
    }
    if (strcasecmp(attributeName, "ScaleFactorOfLowerLimit") == 0) {
      attributeValue = toString(mScaleFactorOfLowerLimit);
      return true;
    }
    if (strcasecmp(attributeName, "ScaledValueOfLowerLimit") == 0) {
      attributeValue = toString(mScaledValueOfLowerLimit);
      return true;
    }
    if (strcasecmp(attributeName, "ScaleFactorOfUpperLimit") == 0) {
      attributeValue = toString(mScaleFactorOfUpperLimit);
      return true;
    }
    if (strcasecmp(attributeName, "ScaledValueOfUpperLimit") == 0) {
      attributeValue = toString(mScaledValueOfUpperLimit);
      return true;
    }
    return false;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method is used for checking if the attribute value matches to the given value.

    \param attributeName  The name of the attribute.
    \param attributeValue The value of the attribute (string).
*/

bool ProbabilitySettings::hasAttributeValue(const char *attributeName, const char *attributeValue) const {
  try {
    if (attributeName == nullptr || attributeValue == nullptr)
      return false;
    if (strcasecmp(attributeName, "ForecastProbabilityNumber") == 0 && strcasecmp(attributeValue, toString(mForecastProbabilityNumber).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "TotalNumberOfForecastProbabilities") == 0 && strcasecmp(attributeValue, toString(mTotalNumberOfForecastProbabilities).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "ProbabilityType") == 0 && strcasecmp(attributeValue, toString(mProbabilityType).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "ScaleFactorOfLowerLimit") == 0 && strcasecmp(attributeValue, toString(mScaleFactorOfLowerLimit).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "ScaledValueOfLowerLimit") == 0 && strcasecmp(attributeValue, toString(mScaledValueOfLowerLimit).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "ScaleFactorOfUpperLimit") == 0 && strcasecmp(attributeValue, toString(mScaleFactorOfUpperLimit).c_str()) == 0)
      return true;
    if (strcasecmp(attributeName, "ScaledValueOfUpperLimit") == 0 && strcasecmp(attributeValue, toString(mScaledValueOfUpperLimit).c_str()) == 0)
      return true;
    return false;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method prints the content of the current object into the given stream.

    \param ostream      The output stream.
    \param level        The print level (used when printing multi-level structures).
    \param optionFlags  The printing options expressed in flag-bits.
*/

void ProbabilitySettings::print(std::ostream &stream, uint level, uint optionFlags) const {
  try {
    stream << space(level) << "ProbabilitySettings\n";
    stream << space(level) << "- ForecastProbabilityNumber = " << toString(mForecastProbabilityNumber) << "\n";
    stream << space(level) << "- TotalNumberOfForecastProbabilities = " << toString(mTotalNumberOfForecastProbabilities) << "\n";
    stream << space(level) << "- ProbabilityType = " << toString(mProbabilityType) << "\n";
    stream << space(level) << "- ScaleFactorOfLowerLimit = " << toString(mScaleFactorOfLowerLimit) << "\n";
    stream << space(level) << "- ScaledValueOfLowerLimit = " << toString(mScaledValueOfLowerLimit) << "\n";
    stream << space(level) << "- ScaleFactorOfUpperLimit = " << toString(mScaleFactorOfUpperLimit) << "\n";
    stream << space(level) << "- ScaledValueOfUpperLimit = " << toString(mScaledValueOfUpperLimit) << "\n";
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method counts the hash value of the current object. */

T::Hash ProbabilitySettings::countHash() const {
  try {
    std::size_t seed = 0;
    if (mForecastProbabilityNumber)
      boost::hash_combine(seed, *mForecastProbabilityNumber);
    if (mTotalNumberOfForecastProbabilities)
      boost::hash_combine(seed, *mTotalNumberOfForecastProbabilities);
    if (mProbabilityType)
      boost::hash_combine(seed, *mProbabilityType);
    if (mScaleFactorOfLowerLimit)
      boost::hash_combine(seed, *mScaleFactorOfLowerLimit);
    if (mScaledValueOfLowerLimit)
      boost::hash_combine(seed, *mScaledValueOfLowerLimit);
    if (mScaleFactorOfUpperLimit)
      boost::hash_combine(seed, *mScaleFactorOfUpperLimit);
    if (mScaledValueOfUpperLimit)
      boost::hash_combine(seed, *mScaledValueOfUpperLimit);
    return seed;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mForecastProbabilityNumber} attribute. */

const T::UInt8_opt &ProbabilitySettings::getForecastProbabilityNumber() const {
  try {
    return mForecastProbabilityNumber;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mTotalNumberOfForecastProbabilities} attribute. */

const T::UInt8_opt &ProbabilitySettings::getTotalNumberOfForecastProbabilities() const {
  try {
    return mTotalNumberOfForecastProbabilities;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mProbabilityType} attribute. */

const T::UInt8_opt &ProbabilitySettings::getProbabilityType() const {
  try {
    return mProbabilityType;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mScaleFactorOfLowerLimit} attribute. */

const T::Int8_opt &ProbabilitySettings::getScaleFactorOfLowerLimit() const {
  try {
    return mScaleFactorOfLowerLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mScaledValueOfLowerLimit} attribute. */

const T::Int32_opt &ProbabilitySettings::getScaledValueOfLowerLimit() const {
  try {
    return mScaledValueOfLowerLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mScaleFactorOfUpperLimit} attribute. */

const T::Int8_opt &ProbabilitySettings::getScaleFactorOfUpperLimit() const {
  try {
    return mScaleFactorOfUpperLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

/*! \brief The method returns the value of the {@link mScaledValueOfUpperLimit} attribute. */

const T::Int32_opt &ProbabilitySettings::getScaledValueOfUpperLimit() const {
  try {
    return mScaledValueOfUpperLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setForecastProbabilityNumber(T::UInt8_opt forecastProbabilityNumber) {
  try {
    mForecastProbabilityNumber = forecastProbabilityNumber;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setTotalNumberOfForecastProbabilities(T::UInt8_opt totalNumberOfForecastProbabilities) {
  try {
    mTotalNumberOfForecastProbabilities = totalNumberOfForecastProbabilities;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setProbabilityType(T::UInt8_opt probabilityType) {
  try {
    mProbabilityType = probabilityType;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setScaleFactorOfLowerLimit(T::Int8_opt scaleFactorOfLowerLimit) {
  try {
    mScaleFactorOfLowerLimit = scaleFactorOfLowerLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setScaledValueOfLowerLimit(T::Int32_opt scaledValueOfLowerLimit) {
  try {
    mScaledValueOfLowerLimit = scaledValueOfLowerLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setScaleFactorOfUpperLimit(T::Int8_opt scaleFactorOfUpperLimit) {
  try {
    mScaleFactorOfUpperLimit = scaleFactorOfUpperLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

void ProbabilitySettings::setScaledValueOfUpperLimit(T::Int32_opt scaledValueOfUpperLimit) {
  try {
    mScaledValueOfUpperLimit = scaledValueOfUpperLimit;
  } catch (...) {
    throw Fmi::Exception(BCP, "Operation failed", nullptr);
  }
}

} // namespace GRIB2
} // namespace SmartMet
