// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'StretchingSettingsImpl.*' files.
// ***********************************************************************

#include "StretchingSettings.h"
#include "../../common/Exception.h"
#include "../../common/GeneralDefinitions.h"
#include "../../common/GeneralFunctions.h"
#include <boost/functional/hash.hpp>
#include <iostream>

namespace SmartMet {
namespace GRIB2 {

/*! \brief The constructor of the class. */

StretchingSettings::StretchingSettings() {
  try {
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The destructor of the class. */

StretchingSettings::~StretchingSettings() {
  try {
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method reads and initializes all data related to the current object.

        \param memoryReader  This object controls the access to the memory mapped file.
*/

void StretchingSettings::read(MemoryReader &memoryReader) {
  try {
    mLatitudeOfThePoleOfStretching = memoryReader.read_Int32_opt();
    mLongitudeOfThePoleOfStretching = memoryReader.read_Int32_opt();
    mStretchingFactorScaled = memoryReader.read_UInt32_opt();
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method is used for collecting the current class attributeList.

    \param prefix         The prefix of the each attributeList parameter.
    \param attributeList  The attributeList storage.
*/

void StretchingSettings::getAttributeList(std::string prefix, T::AttributeList &attributeList) const {
  try {
    char name[300];
    sprintf(name, "%sStretchingSettings.LatitudeOfThePoleOfStretching", prefix.c_str());
    attributeList.addAttribute(name, toString(mLatitudeOfThePoleOfStretching));
    sprintf(name, "%sStretchingSettings.LongitudeOfThePoleOfStretching", prefix.c_str());
    attributeList.addAttribute(name, toString(mLongitudeOfThePoleOfStretching));
    sprintf(name, "%sStretchingSettings.StretchingFactorScaled", prefix.c_str());
    attributeList.addAttribute(name, toString(mStretchingFactorScaled));
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method prints the content of the current object into the given stream.

    \param ostream      The output stream.
    \param level        The print level (used when printing multi-level structures).
    \param optionFlags  The printing options expressed in flag-bits.
*/

void StretchingSettings::print(std::ostream &stream, uint level, uint optionFlags) const {
  try {
    stream << space(level) << "StretchingSettings\n";
    stream << space(level) << "- LatitudeOfThePoleOfStretching = " << toString(mLatitudeOfThePoleOfStretching) << "\n";
    stream << space(level) << "- LongitudeOfThePoleOfStretching = " << toString(mLongitudeOfThePoleOfStretching) << "\n";
    stream << space(level) << "- StretchingFactorScaled = " << toString(mStretchingFactorScaled) << "\n";
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method counts the hash value of the current object. */

T::Hash StretchingSettings::countHash() {
  try {
    std::size_t seed = 0;
    if (mLatitudeOfThePoleOfStretching)
      boost::hash_combine(seed, *mLatitudeOfThePoleOfStretching);
    if (mLongitudeOfThePoleOfStretching)
      boost::hash_combine(seed, *mLongitudeOfThePoleOfStretching);
    if (mStretchingFactorScaled)
      boost::hash_combine(seed, *mStretchingFactorScaled);
    return seed;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method returns the value of the {@link mLatitudeOfThePoleOfStretching} attribute. */

const T::Int32_opt &StretchingSettings::getLatitudeOfThePoleOfStretching() const {
  try {
    return mLatitudeOfThePoleOfStretching;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method returns the value of the {@link mLongitudeOfThePoleOfStretching} attribute. */

const T::Int32_opt &StretchingSettings::getLongitudeOfThePoleOfStretching() const {
  try {
    return mLongitudeOfThePoleOfStretching;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

/*! \brief The method returns the value of the {@link mStretchingFactorScaled} attribute. */

const T::UInt32_opt &StretchingSettings::getStretchingFactorScaled() const {
  try {
    return mStretchingFactorScaled;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

void StretchingSettings::setLatitudeOfThePoleOfStretching(T::Int32_opt latitudeOfThePoleOfStretching) {
  try {
    mLatitudeOfThePoleOfStretching = latitudeOfThePoleOfStretching;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

void StretchingSettings::setLongitudeOfThePoleOfStretching(T::Int32_opt longitudeOfThePoleOfStretching) {
  try {
    mLongitudeOfThePoleOfStretching = longitudeOfThePoleOfStretching;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

void StretchingSettings::setStretchingFactorScaled(T::UInt32_opt stretchingFactorScaled) {
  try {
    mStretchingFactorScaled = stretchingFactorScaled;
  } catch (...) {
    throw SmartMet::Spine::Exception(BCP, exception_operation_failed, NULL);
  }
}

} // namespace GRIB2
} // namespace SmartMet
