// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'StretchedRotatedLatLonImpl.*' files.
// ***********************************************************************

#pragma once
#include "../../common/AttributeList.h"
#include "../../common/DataWriter.h"
#include "../../common/MemoryReader.h"
#include "../../grid/Typedefs.h"
#include "../GridDefinition.h"
#include "EarthShapeSettings.h"
#include "LatLonSettings.h"
#include "RotationSettings.h"
#include "StretchingSettings.h"

namespace SmartMet {
namespace GRIB2 {
/*! \brief The class is automatically created from the template (3.3).*/

class StretchedRotatedLatLon : public GridDefinition {
public:
  StretchedRotatedLatLon();
  StretchedRotatedLatLon(const StretchedRotatedLatLon &other);
  virtual ~StretchedRotatedLatLon();

  virtual uint getTemplateNumber() const;
  virtual GridDefinition *createGridDefinition() const;
  virtual void read(MemoryReader &memoryReader);
  virtual void write(DataWriter &dataWriter);
  virtual void getAttributeList(std::string prefix, T::AttributeList &attributeList) const;
  virtual void print(std::ostream &stream, uint level, uint optionFlags) const;
  virtual T::Hash countHash();

  EarthShapeSettings *getEarthShape() const;
  void setEarthShape(EarthShapeSettings &earthShape);
  LatLonSettings *getLatLon() const;
  void setLatLon(LatLonSettings &latLon);
  RotationSettings *getRotation() const;
  void setRotation(RotationSettings &rotation);
  StretchingSettings *getStretching() const;
  void setStretching(StretchingSettings &stretching);

protected:
  // # Copyright 2005-2017 ECMWF.
  // #
  // # This software is licensed under the terms of the Apache Licence Version 2.0
  // # which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
  // #
  // # In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
  // # virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
  // #
  //
  // # TEMPLATE 3.3, Stretched and Rotated Latitude/longitude (or equidistant cylindrical, or Plate Carree)
  //
  // include "grib2/template.3.shape_of_the_earth.def";

  mutable EarthShapeSettings mEarthShape;

  // include "grib2/template.3.latlon.def";

  mutable LatLonSettings mLatLon;

  // include "grib2/template.3.rotation.def";

  mutable RotationSettings mRotation;

  // include "grib2/template.3.stretching.def";

  mutable StretchingSettings mStretching;

  //
};

} // namespace GRIB2
} // namespace SmartMet
