// ***********************************************************************
//                      DO NOT EDIT THIS FILE !!!
// ***********************************************************************
//   This file is automatically generated from the grib_api templates. All
//   changes will be overridden. If you want to do permanent changes then
//   you should write them into the 'RotationSettingsImpl.*' files.
// ***********************************************************************

#pragma once
#include "../../common/AttributeList.h"
#include "../../common/DataWriter.h"
#include "../../common/MemoryReader.h"
#include "../../grid/Typedefs.h"

namespace SmartMet {
namespace GRIB1 {
/*! \brief The class is automatically created from the template (grid_rotation).*/

class RotationSettings {
public:
  RotationSettings();
  RotationSettings(const RotationSettings &other);
  virtual ~RotationSettings();

  virtual void getAttributeList(std::string prefix, T::AttributeList &attributeList) const;
  virtual void read(MemoryReader &memoryReader);
  virtual void write(DataWriter &dataWriter);
  virtual void print(std::ostream &stream, uint level, uint optionFlags) const;
  virtual T::Hash countHash();

  std::int24_t getLatitudeOfSouthernPole() const;
  void setLatitudeOfSouthernPole(std::int24_t latitudeOfSouthernPole);
  std::int24_t getLongitudeOfSouthernPole() const;
  void setLongitudeOfSouthernPole(std::int24_t longitudeOfSouthernPole);
  ibmfloat getGeography_angleOfRotationInDegrees() const;
  void setGeography_angleOfRotationInDegrees(ibmfloat geography_angleOfRotationInDegrees);

protected:
  // # Copyright 2005-2017 ECMWF.
  // #
  // # This software is licensed under the terms of the Apache Licence Version 2.0
  // # which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
  // #
  // # In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
  // # virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
  // #
  //
  // signed[3] latitudeOfSouthernPole : edition_specific;

  std::int24_t mLatitudeOfSouthernPole;

  // meta  geography.latitudeOfSouthernPoleInDegrees   scale(latitudeOfSouthernPole ,oneConstant,grib1divider,truncateDegrees) : dump;
  //
  // signed[3] longitudeOfSouthernPole : edition_specific ;

  std::int24_t mLongitudeOfSouthernPole;

  // meta  geography.longitudeOfSouthernPoleInDegrees   scale(longitudeOfSouthernPole ,oneConstant,grib1divider,truncateDegrees) : dump;
  //
  // ibmfloat geography.angleOfRotationInDegrees : dump;

  ibmfloat mGeography_angleOfRotationInDegrees;

  //
  // alias angleOfRotation =angleOfRotationInDegrees;
  // alias is_rotated_grid = one;
};

} // namespace GRIB1
} // namespace SmartMet
